project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: classification.qmd
        text: Clasificacion
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center